services:
  flask:
    container_name: blog-app
    build:
      context: .
    env_file:
      - .env

    depends_on:
       mysql:
         condition: service_healthy

    ports:
      - 8000:5000
    networks:
      - flask-sql

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./query:/docker-entrypoint-initdb.d
      - two-tier:/var/lib/mysql
    container_name: mysqldb
    image: mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
      - flask-sql

volumes:
  two-tier: 
networks:
  flask-sql:
    driver: bridge
