apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask-service
  namespace:  {{ .Values.namespace }}
  labels:
    app: flask-mysql-app
spec:
  selector:
    name: flask-app-pod
  type: NodePort
  ports:
    - name: http-port
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
