apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
  namespace:  {{ .Values.namespace }}
spec:
  selector:
    name: mysql-app-pod
  type: {{ .Values.mysqlService.type }}
  ports:
    - name: http-port
      port: {{ .Values.mysqlService.port }}
      targetPort: {{ .Values.mysqlService.targetPort }}

