apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
spec:
  selector:
    name: mysql-app-pod
  type: {{ default "ClusterIP" .Values.serviceBackend.type}}
  ports:
    - name: http-port
      port: {{ .Values.serviceBackend.port }}
      targetPort: {{ .Values.serviceBackend.targetPort }}

