apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv-mysql
  labels:
      name: flask-mysql-app
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql