apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  labels:
    name: flask-mysql-app
spec:
  claimRef:
    name: pvc-mysql
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql
  storageClassName: localstorage